-- MySQL Script generated by MySQL Workbench
-- 01/10/16 17:14:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `privatesaudioweb` DEFAULT CHARACTER SET utf8 ;
USE `privatesaudioweb` ;

-- -----------------------------------------------------
-- Table `privatesaudioweb`.`tb_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `privatesaudioweb`.`tb_user` ;

CREATE TABLE IF NOT EXISTS `privatesaudioweb`.`tb_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `insert_date` DATETIME NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `privatesaudioweb`.`tb_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `privatesaudioweb`.`tb_role` ;

CREATE TABLE IF NOT EXISTS `privatesaudioweb`.`tb_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `privatesaudioweb`.`tb_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `privatesaudioweb`.`tb_user_role` ;

CREATE TABLE IF NOT EXISTS `privatesaudioweb`.`tb_user_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`id`)
    REFERENCES `privatesaudioweb`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_id`
    FOREIGN KEY (`id`)
    REFERENCES `privatesaudioweb`.`tb_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
